<a href="https://colab.research.google.com/github/NidalNaaz/Int.-Msc-CS-AI-DS/blob/main/MachineLearning_LabCycle1Q5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Manually creating the dataset
data = [
    ['milk', 'bread', 'butter'],
    ['milk', 'bread'],
    ['bread', 'butter'],
    ['milk', 'bread', 'butter'],
    ['bread', 'butter'],
    ['milk', 'butter'],
    ['milk', 'bread', 'butter'],
    ['bread', 'butter'],
    ['milk', 'bread']
]

# Converting to a pandas DataFrame for easier manipulation
df = pd.DataFrame(data, columns=['item1', 'item2', 'item3'])
df = df.apply(lambda x: x.dropna().tolist(), axis=1)

# Show the dataset
df.head()

0    [milk, bread, butter]
1            [milk, bread]
2          [bread, butter]
3    [milk, bread, butter]
4          [bread, butter]
dtype: object

In [ ]:
# Display the first few transactions
print("First few transactions:")
print(df.head())

# Check the total number of transactions
print(f"\nTotal number of transactions: {len(df)}")

# Check the unique items in the dataset
all_items = [item for sublist in df for item in sublist]
unique_items = set(all_items)
print(f"\nTotal unique items: {len(unique_items)}")
print(f"Unique items: {unique_items}")

First few transactions:
0    [milk, bread, butter]
1            [milk, bread]
2          [bread, butter]
3    [milk, bread, butter]
4          [bread, butter]
dtype: object

Total number of transactions: 9

Total unique items: 3
Unique items: {'butter', 'milk', 'bread'}

In [ ]:
from mlxtend.preprocessing import TransactionEncoder

# Convert dataframe to list of lists
transactions = df.tolist()

# Apply TransactionEncoder
te = TransactionEncoder()
te_array = te.fit(transactions).transform(transactions)

# Create new dataframe
encoded_df = pd.DataFrame(te_array, columns=te.columns_)

print(encoded_df.head())

   bread  butter   milk
0   True    True   True
1   True   False   True
2   True    True  False
3   True    True   True
4   True    True  False

In [ ]:
# Calculate support for each individual item
support = encoded_df.mean()

print("Support for each item:\n")
print(support)

Support for each item:

bread     0.888889
butter    0.777778
milk      0.666667
dtype: float64

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from mlxtend.frequent_patterns import apriori

# Apply Apriori
frequent_itemsets = apriori(encoded_df,
                            min_support=0.5,
                            use_colnames=True)

print(frequent_itemsets)

    support         itemsets
0  0.888889          (bread)
1  0.777778         (butter)
2  0.666667           (milk)
3  0.666667  (butter, bread)
4  0.555556    (milk, bread)

In [ ]:
from mlxtend.frequent_patterns import association_rules

# Generate association rules
rules = association_rules(frequent_itemsets,
                          metric="confidence",
                          min_threshold=0.7)

# Display rules
rules[['antecedents', 'consequents', 'support', 'confidence', 'lift']]

  antecedents consequents   support  confidence      lift
0    (butter)     (bread)  0.666667    0.857143  0.964286
1     (bread)    (butter)  0.666667    0.750000  0.964286
2      (milk)     (bread)  0.555556    0.833333  0.937500

In [ ]:
#The generated association rules show high confidence values (> 0.75), indicating that items such as butter and milk are frequently purchased with bread. However, the lift values are close to 1, suggesting that the associations are not particularly strong and may be influenced by the high overall frequency of bread purchases.